### ISSUE TITLE
Add feature to url shortcut

### ISSUE THREAD

**Issue by StephD** [mdickin/vscode-markdown-shortcuts#10]
Hello,

In my way to work, I'm used to type the url in the *.md file and I tought that your shortcut allow me to "renamed" the url and give it the name I typed.
But in the actual shortcut, it's the opposite, have to write a text and then allow the redirection to an url.

In my way, I'm force to copy the actual url and paste it as text to allow the redirection.

To allow my way to work, there is another way to url : <url>  (Shortcut for "[url](url)")
It would be great to put <> around the selected text (because it's an url for me) when no text is typed in the textbox.

Did I was clear enought in my explaination :) ?

Thanks you

**Comment by mdickin** [comment]
Ok, I think I understand now. You want to highlight text in the document and convert it to a link (by wrapping it with `<>`)

So the process would look something like:
1. Select text `http://www.google.com` in document
2. Right-click and select "Convert to hyperlink" (could also be a keyboard command)
3. Selection is changed to `<http://www.google.com>`

Does that sound correct?

**Comment by StephD** [comment]
Yes it is :)

**Comment by mdickin** [comment]
This is now implemented in v0.6.0. Highlight a URL and press ctrl+L and it will add angle brackets to the selection

**Comment by StephD** [comment]
Thanks.
It seams to work only with url start with http://.  I just test and you are right because "<www.google.com>" doesn't work.

If I can ask another feature about url shortcut. 
Is it possible to check the presence of "http://" before the link-url and if not present, add it?

1. Write "test"
2. Hightline and use ctrl+L
3. Write "www.google.com" in the text area
4. See "]test](http://www.google.com)" as replaced text (with [])

Thanks

**Comment by mdickin** [comment]
For your new request, I'm afraid it would get in the way of use cases. For example, my site pumlhorse.com is hosted on GitHub and is generated through Markdown files. It allows me to use relative URLs for linking internal pages, so something like `[Frequently Asked Questions](../faq.md)`.

Even in normal GitHub, you can use relative paths like so: `[readme](../blob/master/README.md)` -> [readme](../blob/master/README.md). If I were to implement your request, these relative paths would be erroneously prepended with "http://". Even checking if it starts with a period wouldn't be accurate. If README.md links to CHANGELOG.md, should it understand that `.md` is a file extension and not a TLD?

Unfortunately, this seems like one of those cases where it's easiest to just type a few extra characters. Thank you for the input though!

**Comment by StephD** [comment]
No worry :)

Good job
