### ISSUE TITLE
Add shortcut for insert image

### ISSUE THREAD

**Issue by ngtrian** [mdickin/vscode-markdown-shortcuts#12]
Can you add default shortcut insert image such as:

`![](image_url_copied)`

**Comment by ngtrian** [comment]
Maybe works similar to insert link!

**Comment by mdickin** [comment]
I think that's a great idea. If there is text selected, it'll be used as the link, otherwise prompt for the URL like normal. Thanks for the recommendation!

**Comment by mdickin** [comment]
Released in v0.7.0. Ctrl+shift+L is the shortcut. Thanks again for the idea!
