### ISSUE TITLE
Support alt text for insert image

### ISSUE THREAD

**Issue by ngtrian** [mdickin/vscode-markdown-shortcuts#13]
You may add support for alt text for insert image, which automatically behaves in each case.
example:
- if the text is selected, the result is: `![Text_selected] (image_url)`
- If the link is selected or empty, the result is: `![](Image_url)`

Again, thank you very much for this plugin

**Comment by ngtrian** [comment]
Escape button seem doesn't working in insert image

**Comment by mdickin** [comment]
Good catch, thanks! That'll teach me to clean up code and not test it afterward.

I've fixed that issue and added alt text support in v0.7.1.
