### ISSUE TITLE
Missing Header commands

### ISSUE THREAD

**Issue by mlewand** [mdickin/vscode-markdown-shortcuts#14]
I'm looking for commands like `md-shortcut.toggleTitleH1`, and can't seem to find it in commands pallete.

Now looking at `package.json` I see that the plugin does not declare to contribute this commands, am I missing something?

**Comment by mdickin** [comment]
Looks like it's only declared programmatically. I just checked and you can still bind a keystroke to it. I'll keep this as a bug and make sure it (and the rest of the missing commands) get declared in `package.json`. Thanks!

**Comment by mdickin** [comment]
Also, if you weren't aware, Markdown Shortcuts provides its own command palette. You can use it by pressing `ctrl+M ctrl+M`

**Comment by mlewand** [comment]
Ohh, my didn't notice it, thanks! :D

**Comment by mdickin** [comment]
Resolved in v0.8.0
