### ISSUE TITLE
Toggle block doesnt work for a collapsed selection

### ISSUE THREAD

**Issue by mlewand** [mdickin/vscode-markdown-shortcuts#15]
1. Open a new markdown file.
1. Set contents to the following (where `^` marks a collapsed range position):
  ```markdown
  # foo

  ba^r
  ```
1. Press `ctrl+m, ctrl+c` to insert a code block.

Code block gets inserted.

Nothing happens, extension throws na exception.

> Running the contributed command:'md-shortcut.toggleCodeBlock' failed.

**Comment by mdickin** [comment]
Hmm, didn't mean to close this...please test the latest code and make sure I didn't break it on your machine.

**Comment by mlewand** [comment]
I referenced it to close with one of commit messages, as fix for it was included in the PR.

It's covered by [one test case](https://github.com/mdickin/vscode-markdown-shortcuts/blob/d7b70fec759e9489f1d827a8008c8f660380f944/test/extension.test.js#L95-L97) so it has to work :)

**Comment by mdickin** [comment]
Resolved in v0.8.0
