### ISSUE TITLE
[BUG] Shortkeys in context menu

### ISSUE THREAD

**Issue by Fred-Vatin** [mdickin/vscode-markdown-shortcuts#29]
VS Code version | OS | Extension version
------------------ | ---- | ----
1.14.0 and 1.15.0 -insider | Win 10 x64 pro (french) 14393 | 0.8.1

## Steps to reproduce

Right click to display context menu in a **markdown** file.

## Results

Screenshot speaks for itself:

![md](https://user-images.githubusercontent.com/22337329/28129272-00909bc8-6733-11e7-8c98-2fcaea3278a7.PNG)

But note that the shortkeys work as expected despite the cosmetic issue and another extension share the same [issue](https://github.com/AlanWalk/markdown-toc/issues/29): [Markdown TOC](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc)

If it is a VSCode bug, refer its issue number so we can go to vote for it.

Thanks

**Comment by mdickin** [comment]
Opened issue: Microsoft/vscode#30617

Thanks for bringing this to my attention

**Comment by mdickin** [comment]
Looks like this is an issue with Electron: electron/electron#5398
