### ISSUE TITLE
Highlight with <mark>

### ISSUE THREAD

**Issue by Danilux** [mdickin/vscode-markdown-shortcuts#31]
Hi, is there a way to create a markdown shortcut to add highlight to elements, like instead of wrapping the element with `<mark>element</mark>`, I'd like to write something like =element=, and that could trigger the `<mark>element</mark>`, sorry if this is not the place to ask for such a thing, thanks

**Comment by mdickin** [comment]
I'm not sure I follow what you're asking. Wrapping text like `=element=` isn't part of the Markdown specification or Github Flavored Markdown. Are you expecting `=element=` to be rendered in a specific way? Or are you asking for the ability to wrap selected text with a user defined pattern?

**Comment by Danilux** [comment]
I'm sorry, my english is not that good, I understand =element= is not part of the spec, just wondering if I could implement a shortcut, well, more like a snippet and add it to the context menu of markdown-shorcut, that would allow me to click it and it'd wrap the text with a `<mark></mark>` element

**Comment by mdickin** [comment]
No need to apologise, your English is very good - much better than I can speak any other language!

I think we're saying the same thing, and I had thought about a feature like this before, though I'm still not sure it should go in this extension. Thanks for the suggestion!

**Comment by mdickin** [comment]
I wonder, would this extension solve your needs? <https://marketplace.visualstudio.com/items?itemName=sifue.surrounding>
