### ISSUE TITLE
"Ctrl+Shift+L" for images conflicts with default keybinding for editor.action.selectHighlights

### ISSUE THREAD

**Issue by Dod9er** [mdickin/vscode-markdown-shortcuts#32]
Hi,
one of the default keybindings I use quite often is "Ctrl+Shift+L" in order to change a string at multiple locations. Check editor.action.selectHighlights at https://code.visualstudio.com/docs/getstarted/keybindings for reference.
Is it possble to change this keybinding for markdown-shortcuts on my own ? Didn´t find the necessary config.

**Comment by mdickin** [comment]
Sorry about that!

You can remap that shortcut if you go to File > Preferences > Keyboard Shortcuts.

Search for "ctrl+shift+L" and it will bring up the conflicting bindings. You can remap it, remove it, whatever you want.

![image](https://user-images.githubusercontent.com/16612667/30327837-18b08ff2-9793-11e7-9f36-bca215096f74.png)

**Comment by Dod9er** [comment]
Ahh, ok. I´m quite new to VSCode, as you see. Thanks for your hint :+1:
