### ISSUE TITLE
Change predefined shortcuts

### ISSUE THREAD

**Issue by natakazakova** [mdickin/vscode-markdown-shortcuts#34]
Hi!
I need specific shortcuts for DocFX flavored markdown, e.g. warnings and notes, xref links and so on [DocFX Flavored Markdown](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#note-warningtipimportant).
Can I change some predefined shortcuts? If yes, please tell me how :)

**Comment by mdickin** [comment]
@natakamyshnikova, I apologize for my late response.

I think #32 answers your question. Please let me know if I misunderstood.

**Comment by secsilm** [comment]
Hi @mdickin , I have same situation. I want to use `*` instead of `_` when I press `Ctrl` + `I`. Is there a solution?

**Comment by mdickin** [comment]
@secsilm, I've added this functionality per issue #26 in version v0.9.0. Thanks!
