### ISSUE TITLE
Bullet points with dash

### ISSUE THREAD

**Issue by anibalsanchez** [mdickin/vscode-markdown-shortcuts#36]
By default, the Bullet points are generated with an asterisk.

Is there any way to change the default to use a dash?

**Comment by FFengIll** [comment]
I think it should allow to config using + - *

**Comment by mdickin** [comment]
As of v0.9.0, bullet points can be configured to use plus sign, dash, or asterisk. Thanks for the contribution, @FFengIll!

**Comment by anibalsanchez** [comment]
Thank you!

**Comment by timdhoffmann** [comment]
Thanks!
