### ISSUE TITLE
Toggle multiline citations

### ISSUE THREAD

**Issue by jannismain** [mdickin/vscode-markdown-shortcuts#38]
When having a multiline citation, a command to quickly convert it to a proper markdown citation (prepend `>` before each line) would greatly improve the current workflow (selection of several lines and typing the `>` manually).

_Example:_

```
This is a
multiline
citation
```

convert to:

```
> This is a
> multiline
> citation
```

Markdown Output:
> This is a
> multiline
> citation

**Comment by mdickin** [comment]
Shortcut added in v0.9.0. Thanks @FFengIll!

**Comment by mdickin** [comment]
And thank you for the recommendation, @mainczjs!
