### ISSUE TITLE
Find surrounding word

### ISSUE THREAD

**Issue by mdickin** [mdickin/vscode-markdown-shortcuts#5]
When cursor is placed inside a word (but word is not selected), use that word as the selection.

Example:
1. Type "embolden"
2. Place cursor between "b" and "o"
3. Press ctrl+b
Expected: text is replaced with "**embolden**"

**Comment by mlewand** [comment]
I think that a great addition would be for block-kind of commands to wrap the whole line, so you have selection like:
```
Some ran^dom text
```
And press toggle ordered list, it makes:
```
1. Some ran^dom text
```

**Comment by mdickin** [comment]
Resolved in v0.8.0
