### ISSUE TITLE
markdownShortcuts.languages doesn't seem to work

### ISSUE THREAD

**Issue by sebw** [mdickin/vscode-markdown-shortcuts#50]
Some options are useful for Asciidoc.

I'm trying to enable the extension for `asciidoc` language, but it doesn't work.

My `settings.json`:

```
    "markdownShortcuts.languages": [
      "markdown",
      "asciidoc"
    ]
```

**Comment by mdickin** [comment]
Hi @sebw , do you have an Asciidoc extension installed in VSCode? I just installed [AsciiDoc](https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode), changed my settings as you showed, and it worked fine.

When you open the file you're trying to edit, do you see "AsciiDoc" in the lower right corner?

![image](https://user-images.githubusercontent.com/16612667/53171727-2cddf680-35a9-11e9-99af-b7fc9bafc752.png)

**Comment by sebw** [comment]
Hi @mdickin,

Just got home and synced my settings and extensions back to my Mac and it works there.

Problem is on Fedora 29. I will investigate further and report back.

**Comment by sebw** [comment]
Alright, so today I'm checking on Fedora and it works, while I didn't change anything.

PEBKAC!

Thanks for the extension, very useful for me!

**Comment by mdickin** [comment]
Excellent, thanks for following up, I'm glad to hear that it's working and that you enjoy the extension!
