### ISSUE TITLE
Is that possible to make this extension like stackedit or git markdown style?

### ISSUE THREAD

**Issue by axiqia** [mdickin/vscode-markdown-shortcuts#56]
-  Keyboard shortcut
` ctrl + shift + k` for code block
` ctrl + shift + L` for link

I think` ctrl+M ctrl+B` is too complex for user. At least, for me :)

- menu
![image](https://user-images.githubusercontent.com/22564578/68391476-b1f25580-01a2-11ea-8661-9da5854f4f7b.png)

I have pulled[ one request ](https://github.com/mdickin/vscode-markdown-shortcuts/pull/55)for cite icon, and I'd to add more.

https://stackedit.io/app#

**Comment by mdickin** [comment]
Hi @axiqia, you can easily change the keyboard shortcuts for these commands in the Keyboard Shortcuts menu.

![image](https://user-images.githubusercontent.com/16612667/68546733-49bc9300-039f-11ea-96f5-28c340200fe6.png)

I don't feel comfortable making a change to the extension now, as there are many users that may have gotten used to the commands as they are now.

**Comment by axiqia** [comment]
yep, I agree. How about the menu? @mdickin

**Comment by mdickin** [comment]
Sorry yes, I am perfectly fine with adding icons for other commands. Please just make sure they're defaulted to hidden
