### ISSUE TITLE
very nice experience @V0.4, and I find table vs table with header has no difference,pls check

### ISSUE THREAD

**Issue by wenbaofu** [mdickin/vscode-markdown-shortcuts#7]
1. you also find the preview problem of VsCode?I raise a issue for it [issue for vscode](https://github.com/Microsoft/vscode/issues/15231)
2. pls help tell me how you capture the screen for demo? which tool are you using, very cool....

**Comment by mdickin** [comment]
I personally use http://screentogif.codeplex.com/ for screen captures.

There is no difference between "Add table" and "Add table with header" if you don't have anything selected. However, note the behavior here:

![](https://raw.githubusercontent.com/mdickin/vscode-markdown-shortcuts/master/media/demo/table_with_header.gif)

If you selected "Add table" instead, it would generate default column names for each column.
